apiVersion: v1
kind: Service
metadata:
  name: grpc-server
spec:
  type: LoadBalancer
  selector:
    app: grpc-server
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
      nodeport: 31415