// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: CacheService.proto

package com.dhan.cache;

public final class CacheServiceOuterClass {
  private CacheServiceOuterClass() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_dhan_cache_PingRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_dhan_cache_PingRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_dhan_cache_PingResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_dhan_cache_PingResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_dhan_cache_GetValueRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_dhan_cache_GetValueRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_dhan_cache_GetValueResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_dhan_cache_GetValueResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_dhan_cache_PutValueRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_dhan_cache_PutValueRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_dhan_cache_PutValueResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_dhan_cache_PutValueResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\022CacheService.proto\022\016com.dhan.cache\"\036\n\013" +
      "PingRequest\022\017\n\007message\030\001 \001(\t\"\037\n\014PingResp" +
      "onse\022\017\n\007message\030\001 \001(\t\"\036\n\017GetValueRequest" +
      "\022\013\n\003key\030\001 \001(\t\"!\n\020GetValueResponse\022\r\n\005val" +
      "ue\030\001 \001(\t\"-\n\017PutValueRequest\022\013\n\003key\030\001 \001(\t" +
      "\022\r\n\005value\030\002 \001(\t\"$\n\020PutValueResponse\022\020\n\010r" +
      "esponse\030\001 \001(\0102\357\001\n\014CacheService\022A\n\004ping\022\033" +
      ".com.dhan.cache.PingRequest\032\034.com.dhan.c" +
      "ache.PingResponse\022M\n\010getValue\022\037.com.dhan" +
      ".cache.GetValueRequest\032 .com.dhan.cache." +
      "GetValueResponse\022M\n\010putValue\022\037.com.dhan." +
      "cache.PutValueRequest\032 .com.dhan.cache.P" +
      "utValueResponseB\002P\001b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_com_dhan_cache_PingRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_com_dhan_cache_PingRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_dhan_cache_PingRequest_descriptor,
        new java.lang.String[] { "Message", });
    internal_static_com_dhan_cache_PingResponse_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_com_dhan_cache_PingResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_dhan_cache_PingResponse_descriptor,
        new java.lang.String[] { "Message", });
    internal_static_com_dhan_cache_GetValueRequest_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_com_dhan_cache_GetValueRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_dhan_cache_GetValueRequest_descriptor,
        new java.lang.String[] { "Key", });
    internal_static_com_dhan_cache_GetValueResponse_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_com_dhan_cache_GetValueResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_dhan_cache_GetValueResponse_descriptor,
        new java.lang.String[] { "Value", });
    internal_static_com_dhan_cache_PutValueRequest_descriptor =
      getDescriptor().getMessageTypes().get(4);
    internal_static_com_dhan_cache_PutValueRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_dhan_cache_PutValueRequest_descriptor,
        new java.lang.String[] { "Key", "Value", });
    internal_static_com_dhan_cache_PutValueResponse_descriptor =
      getDescriptor().getMessageTypes().get(5);
    internal_static_com_dhan_cache_PutValueResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_dhan_cache_PutValueResponse_descriptor,
        new java.lang.String[] { "Response", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
