// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: CacheService.proto

package com.dhan.cache;

public interface DeleteAllValuesRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.dhan.cache.DeleteAllValuesRequest)
    com.google.protobuf.MessageOrBuilder {
}
