// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: CacheService.proto

package com.dhan.cache;

public interface GetKeysRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.dhan.cache.GetKeysRequest)
    com.google.protobuf.MessageOrBuilder {
}
