// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: CacheService.proto

package com.dhan.cache;

public interface PingResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.dhan.cache.PingResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string message = 1;</code>
   * @return The message.
   */
  java.lang.String getMessage();
  /**
   * <code>string message = 1;</code>
   * @return The bytes for message.
   */
  com.google.protobuf.ByteString
      getMessageBytes();
}
