// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: CacheService.proto

package com.dhan.cache;

public interface PutValueResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.dhan.cache.PutValueResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>bool response = 1;</code>
   * @return The response.
   */
  boolean getResponse();
}
